[package]
name = "cpp_utils"
version = "0.1.2"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
description = "Various C++-related types and functions needed for the cpp_to_rust project"
license = "MIT"
repository = "https://github.com/rust-qt/cpp_utils"
