__common: &common
  language: rust
  rust: stable
  cache:
    directories:
    - $HOME/.cargo
    - cpp_to_rust/cpp_to_rust_build_tools/target
    - cpp_to_rust/cpp_to_rust_common/target
    - cpp_to_rust/cpp_to_rust_generator/target
    - cpp_to_rust/cpp_utils/target
    - qt_generator/qt_build_tools/target
    - qt_generator/qt_generator/target
    - qt_generator/qt_generator_common/target


matrix:
  include:
  - <<: *common
    os: linux
    dist: trusty
    script:
    - sudo apt-get install llvm-3.8 libclang-3.8-dev --yes --force-yes
    - ci/travis/run.bash
  - <<: *common
    os: osx
    script: ci/travis/run.bash

