matrix:
  include:
  - os: linux
    dist: trusty
    language: rust
    rust: stable
    script: sudo tests/travis.bash
  - os: osx
    language: rust
    rust: stable
    script: tests/travis.bash

