build_script: ci\appveyor\run.bat

cache:
- 'cpp_to_rust\cpp_to_rust_build_tools\target'
- 'cpp_to_rust\cpp_to_rust_common\target'
- 'cpp_to_rust\cpp_to_rust_generator\target'
- 'cpp_to_rust\cpp_utils\target'
- 'qt_generator\qt_build_tools\target'
- 'qt_generator\qt_generator\target'
- 'qt_generator\qt_generator_common\target'
- '%USERPROFILE%\.cargo'
- '%USERPROFILE%\.multirust'

