[package]
name = "cpp_to_rust"
version = "0.1.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
build = "build.rs"

[dependencies]
serde = "0.8"
serde_json = "0.8"
ansi_term = "0.7"
clang = { git = "https://github.com/KyleMayes/clang-rs" }
regex = "0.1"
rustfmt = "0.5.0"
libc = "0.2"
toml = "0.2"
tempdir = "0.3.5"

[build-dependencies]
serde_codegen = "0.8"
