[package]
name = "cpp_to_rust"
version = "0.1.3"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
build = "build.rs"
description = "Automatic generator of C++ library wrappers"
license = "MIT"
repository = "https://github.com/rust-qt/cpp_to_rust"

[lib]
name = "cpp_to_rust"
path = "src/lib.rs"

[[bin]]
name = "cpp_to_rust_bin"
path = "src/main.rs"

[dependencies]
serde = "0.8"
serde_json = "0.8"
ansi_term = "0.7"
clang = "0.12.0"
regex = "0.1"
rustfmt = "0.5.0"
libc = "0.2"
toml = "0.2"
tempdir = "0.3.5"
num_cpus = "1.0.0"
select = "0.3.0" #html parsing library
csv = "0.14.7"
clap = "~2.10.0"

[build-dependencies]
serde_codegen = "0.8"

[profile.dev]
#opt-level = 3
