[package]
name = "qt_build_tools"
version = "0.1.3"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
license = "MIT"
description = "Build script implementation for Rust Qt crates"

[dependencies]
cpp_to_rust_build_tools = "0.0"
cpp_to_rust_common = "0.0"
qt_generator_common = "0.0"
