[package]
name = "cpp_to_rust_build_tools"
version = "0.0.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]

description = "Build script implementation for C++ library wrappers"
license = "MIT"

[dependencies]
cpp_to_rust_common = { version = "0.0", path = "../../cpp_to_rust/cpp_to_rust_common" }
