[package]
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
build = "build.rs"
name = "rust_ctrt1"
version = "0.0.0"
links = "ctrt1"

[dependencies]
libc = "0.2"
cpp_utils = "0.1"

[build-dependencies]
cpp_to_rust = "0.3"
